### ISSUE TITLE
Unable to obtain iana registry information,

### ISSUE THREAD

**Issue by domainbf** [jqpe/network-tools#1]
I can't get the iana table information. What's the reason? I use Vercel hosting.
abc
View this top-level domain in the root
Fetching data from Iana...

**Comment by jqpe** [comment]
The repository is deployed on Cloudflare and uses Cloudflare Pages functions. You need to adapt the functions code to work in Vercel environment, see [https://vercel.com/docs/functions](https://vercel.com/docs/functions), specifically other frameworks. Some way to fetch Iana outside of browser sandbox is required because of CORS.

When you view an individual TLD the route will perform a GET request to /api/iana/db/abc.html, which is just a proxy that returns the document in https://www.iana.org/domains/root/db/abc.html

If you opt to deploy on Cloudflare (works on free tier):

Build command: `corepack enable && pnpm install --production --frozen-lockfile && pnpm build && pnpm build --mode page-function`
Build output directory: /dist
Build system version: 2 (latest)
Root directory: /

**Comment by domainbf** [comment]
Thank you for your reply.
I use vercel deployment, and I don't understand the functions I call.

Give up, I don't know much about code.

**Comment by jqpe** [comment]
Easiest way to deploy is to use Cloudflare Pages, if you want to use another PAAS it will require some refactoring, and thus understanding of code.

**Comment by domainbf** [comment]
OK, thanks,
